apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: youssefashraf265/todo-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: todo-storage
          mountPath: /app/todo.db   # inside container
          subPath: todo.db          # just the file
      volumes:
      - name: todo-storage
        hostPath:
          path: /data/todo          # on Docker Desktop VM
          type: DirectoryOrCreate
