name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Application-Setup-Testing:
    name: Application Setup and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: Application-Setup-Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t todo-app:latest .
          docker tag todo-app:latest ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

  Kubernetes:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify kubectl
        run: kubectl version --client

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/todo-app -n todo-app
