name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Application-Setup:
    name: Application Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
  Testing-Application:
    name: Run Test Script
    runs-on: ubuntu-latest
    needs: Application-Setup

    steps:
      - name: Run tests
        run: pytest -v

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t todo-app:latest .
          docker tag todo-app:latest ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
  #Kubernetes:
  #  name: Deploy to Kubernetes
  #  runs-on: ubuntu-latest
  #  needs: docker

  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v3
      
